version: '3'
services:
        web_t8:
                image: flask_rice-cubes_t8_v1
                build: .
                ports:
                        - "8048:8080"
                volumes:
                        - persistent_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/T8048_united-rice-cubes/volumes
